version: '3.1'

services:
  tb-db:
    image: mysql:8.0.15
    container_name: mysql
    restart: 'no'
    environment:
      MYSQL_DATABASE: 'dev_tb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev_tb_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'dev_tb_db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'